version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
